version: '3.10'
services:
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      HOST: db
      PORT: 5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 15s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      HOST: db
      PORT: 5432
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
